stages:
  - test
  - build
  - deploy
variables:
  APP_NAME: Netflix-Frontend/netflix



Building_with_Docker:
  stage: build
  before_script:
    - export JSON_VERSION=$(cat package.json | jq -r .version)
    - export APP_VERSION= $JSON_VERSION.$CI_PIPELINE_ID
    - echo "APP_VERSION=$APP_VERSION" >> version.env
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$APP_NAME:$APP_VERSION .
  artifacts:
    reports:
      dotenv: version.env
    
Pushing_to_Registry:
  stage: build
  needs:
    - Bulding_with_Docker
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE/$APP_NAME:APP_VERSION



Testing_with_Sonarcude:
  stage: test
  dependencies : []
  before_script:
    - echo "installing dependencies"
  script:
    - echo "testing the application"